fix: update popover behavior for android
akveo/react-native-ui-kitten pull request #1323
Opened 2021-01-07 13:43 UTC by whitestranger7

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
Fix for #1297

2021-01-08 19:40 UTC, artyorsh requested changes
Let's use optional chaining to simplify code

2021-01-08 19:40 UTC, artyorsh commented on src/components/ui/popover/popover.component.tsx
> +    }
```suggestion
this.hardwareBackSubscription?.remove();
```

2021-01-08 19:40 UTC, artyorsh commented on src/components/ui/popover/popover.component.tsx
> +  private backAction = (): boolean => {
```suggestion
  private onHardwareBackPress = (): boolean => {
```

2021-01-08 19:40 UTC, artyorsh commented on src/components/ui/popover/popover.component.tsx
> +  private backHandler: NativeEventSubscription;
```suggestion
  private hardwareBackSubscription: NativeEventSubscription;
```

2021-01-11 19:09 UTC, artyorsh commented
Closes #1293

2021-01-22 12:08 UTC, malashkevich approved these changes

2021-01-22 12:08 UTC, malashkevich commented on src/components/ui/popover/popover.component.tsx
> +import { StyleSheet, BackHandler, NativeEventSubscription, Platform } from 'react-native';
Multiline

2021-02-08 11:03 UTC, artyorsh approved these changes

2021-02-09 09:24 UTC, merged