feat: add onMonthChange function to the Calendar component
akveo/react-native-ui-kitten pull request #1338
Opened 2021-01-25 17:00 UTC by whitestranger7

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

#### Short description of what this resolves:
Add monthChange functions, which executes per each month update

2021-01-25 17:19 UTC, artyorsh requested changes
We should also add documentation for this prop. Check `RangeCalendar` and `Calendar` components.
Also, I would propose removing `viewMode` check and calling this `onVisibleDateChange` so that it can be more generic.

See #1115

2021-01-25 17:19 UTC, artyorsh commented on src/components/ui/calendar/baseCalendar.component.tsx
> +      this.props.onMonthChange && this.props.onMonthChange(this.state.visibleDate);
```suggestion
      this.props.onMonthChange?.(this.state.visibleDate);
```

2021-01-25 17:19 UTC, artyorsh commented on src/components/ui/calendar/baseCalendar.component.tsx
> +      this.props.onMonthChange && this.state.viewMode.id === 'DATE' && this.props.onMonthChange(this.state.visibleDate);
```suggestion
      this.state.viewMode.id === 'DATE' && this.props.onMonthChange?.(this.state.visibleDate);
```

2021-01-25 17:19 UTC, artyorsh commented on src/components/ui/calendar/baseCalendar.component.tsx
> +      this.props.onMonthChange && this.state.viewMode.id === 'DATE' && this.props.onMonthChange(this.state.visibleDate);
```suggestion
      this.state.viewMode.id === 'DATE' && this.props.onMonthChange?.(this.state.visibleDate);
```

2021-01-28 14:57 UTC, artyorsh approved these changes

2021-02-03 06:05 UTC, Minetorpia commented
As someone who is really looking forward to use this feature, is there an ETA on when this will be usable for everyone?

2021-02-09 10:46 UTC, merged