fix: remove useless margin for input element
akveo/react-native-ui-kitten pull request #1349
Opened 2021-02-11 17:43 UTC by whitestranger7

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:
Closes #1253

2021-02-13 11:24 UTC, artyorsh reviewed
This will break the final look of the component configured with `caption` or `captionIcon` props. Since we don't use this default spacing between caption text and Input field, a user will more likely have to apply it on his own. Which makes Eva not Eva.

Instead, I would suggest removing the `captionIcon` property and wrap the entire `caption` element in `FalsyFC` or better `FalsyText` so we can remove the [caption container view](https://github.com/akveo/react-native-ui-kitten/blob/1f2ed739eabb696e4e0cb7c7eb915142e122167e/src/components/ui/input/input.component.tsx#L302). This way of composing elements will allow us reducing useless spacings between components.

2021-02-18 14:15 UTC, whitestranger7 commented
> This will break the final look of the component configured with `caption` or `captionIcon` props. Since we don't use this default spacing between caption text and Input field, a user will more likely have to apply it on his own. Which makes Eva not Eva.

Im not really sure that I got your point, because I did some tests and this additional `marginTop: 4px` doesn't affect component with `caption` and `captionIcon` props.
<img width="1045" alt="Screenshot 2021-02-18 at 17 12 49" src="https://user-images.githubusercontent.com/36364993/108369645-dc87e680-720c-11eb-9f2f-af33fdffc688.png">

2021-03-15 06:37 UTC, artyorsh requested changes

2021-03-15 06:37 UTC, artyorsh commented on src/components/ui/input/input.component.tsx
> +        )}
FalsyText will work in both cases

2021-03-15 14:21 UTC, malashkevich commented on src/components/ui/input/input.component.tsx
> +        <FalsyText style={evaStyle.captionLabel} component={caption} />
multiline

2021-03-15 14:21 UTC, malashkevich commented on src/components/ui/input/input.spec.tsx
>    it('should render component passed to captionIcon prop', () => {
incorrect name

2021-03-16 15:34 UTC, artyorsh approved these changes

2021-03-23 07:10 UTC, merged