Fix: #1435
akveo/react-native-ui-kitten pull request #1444
Opened 2021-06-04 16:19 UTC by whitestranger7

### Please read and mark the following check list before creating a pull request:

 - [x] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/react-native-ui-kitten/blob/master/CONTRIBUTING.md) guide.
 - [x] I read and followed the [New Feature Checklist](https://github.com/akveo/react-native-ui-kitten/blob/master/DEV_DOCS.md) guide.

 #### Short description of what this resolves:

2021-06-08 13:33 UTC, artyorsh requested changes
Cool :+1: But needs cosmetic changes

2021-06-08 13:33 UTC, artyorsh commented on src/components/ui/datepicker/baseDatepicker.component.tsx
> +      testID={testID}>
please fix the formatting

2021-06-08 13:33 UTC, artyorsh commented on src/components/ui/spinner/spinner.component.tsx
> +      <View testID={this.props.testID} style={containerSize}>
multiline

2021-06-15 15:07 UTC, malashkevich approved these changes

2021-06-15 15:08 UTC, merged